---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url:
sections:
- type: directory
  path: src/pages
  label: Pages
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - page
- type: document
  path: src/data/aboutUs.json
  label: About Us
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm ci
  preview_docker_image: node:14
  mount_path: "/srv"
  working_dir: "/srv/public"
  instant_preview_command: npm run forestry-preview
