---
label: Staff
hide_body: true
fields:
  required: true
- type: field_group_list
  name: sections
  label: Sections
  fields:
  - type: text
    name: header
    label: Header
    required: true
  - type: textarea
    name: content
    label: Content
    required: true
pages:
- src/data/services.json
